name: Improve an Existing Best Practice Guide
description: Suggest improvements to an existing best practice guide
title: "[Improve Existing Best Practice Guide]: "
labels: "enhancement"
body:
  - type: markdown
    attributes:
      value: |
        > _Thanks for filing a new best practice guide request. We appreciate your time and effort. Please answer a few questions._
  - type: dropdown
    id: checked-for-duplicates
    attributes:
      label: Checked for duplicates
      description: Have you checked for duplicate issue tickets?
      multiple: false
      options:
        - "Yes - I've already checked"
        - "No - I haven't checked"
    validations:
      required: yes
  - type: dropdown
    id: guide
    attributes:
      label: Best Practice Guide
      description: Which best practice guide are you looking to improve?
      placeholder: Tell us which guide
      multiple: false
      options:
        - "Continuous Integration"
        - "Continuous Testing"
        - "Documentation"
    validations:
      required: true
  - type: dropdown
    id: sections
    attributes:
      label: Best Practice Guide Sections
      description: Which sections within the best practice guide would you like to improve? Check all that apply.
      multiple: true
      options:
        - "Use Cases"
        - "Trade Studies"
        - "Reference Architectures"
        - "Starter Kits"
  - type: textarea
    id: need
    attributes:
      label: Describe the improvement
      description: Please help us understand the need more fully the ideas you have for improvement to an existing guide. 
      placeholder: Tell us the need
      value: "We need additional use cases such as [...] as well as starter kits for [...]"
    validations:
      required: true
