name: Improve an Existing Best Practice Guide
description: Suggest improvements to an existing best practice guide
title: "[Improve Existing Best Practice Guide]: "
labels: "enhancement"
body:
  - type: markdown
    attributes:
      value: |
        > _Thanks for filing a new best practice guide request. We appreciate your time and effort. Please answer a few questions._
  - type: dropdown
    id: checked-for-duplicates
    attributes:
      label: Checked for duplicates
      description: Have you checked for duplicate issue tickets?
      multiple: false
      options:
        - "Yes - I've already checked"
        - "No - I haven't checked"
    validations:
      required: yes
  - type: dropdown
    id: guide
    attributes:
      label: Best Practice Guide Category
      description: Which best practice guide category are you looking to improve?
      multiple: false
      options:
        - "Software Lifecycle"
        - "Governance"
        - "Documentation"
    validations:
      required: true
  - type: textarea
    id: url
    attributes:
      label: Best practice guide URL
      description: Paste the URL of the best practice guide you want to improve.
      placeholder: URL
      value: "ex. https://nasa-ammos.github.io/slim/docs/guides/documentation/readme/"
    validations:
      required: true
  - type: textarea
    id: need
    attributes:
      label: Describe the improvement
      description: Please help us understand the need more fully the ideas you have for improvement to an existing guide. 
      placeholder: Tell us the need
      value: "We need additional use cases such as [...] as well as starter kits for [...]"
    validations:
      required: true
