# example .github/workflows/unit_tests.yml
# This GitHub Actions workflow is designed to run unit tests on pull requests. It checks out the code repository, sets up Python version 3.11, installs project dependencies including additional test dependencies, and then executes unit tests using pytest with increased verbosity and Gherkin terminal reporter enabled. Modify the Python version or test directory path as needed.

name: Unit Tests 

on: [pull_request]  

jobs:
  unit-tests:  # Defines a job
    runs-on: ubuntu-latest  # Specifies the runner environment

    steps:  
    - uses: actions/checkout@v4  # Checks out the code repository

    - name: Set up Python  
      uses: actions/setup-python@v5  
      with:
        python-version: '3.11'  
        # Modify the following block for other programming languages
        # with:
        #   <language>-version: '<version>'  # Specify the version of the programming language

    - name: Install dependencies 
      run: |  # Executes the following shell commands
        python -m pip install --upgrade pip  # Upgrades pip to the latest version
        pip install -e ".[test]"  # Installs project dependencies in editable mode with additional test dependencies
        # Modify the following block for other programming languages
        # run: |
        #   <install_command>  # Command to install dependencies for the specific language

    - name: Run unit tests  
      run: |  # Executes the following shell commands
        pytest -vv # Runs pytest with increased verbosity
        unity-test/unit  # Specifies the directory where unit tests are located
        # Modify the following block for other programming languages
        # run: |
        #   <test_command>  # Command to run unit tests for the specific language
