name: retype
on:
  push:
    branches:
      - main
  workflow_dispatch:
      

jobs:
  publish:
    name: Publish to retype branch
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: retypeapp/action-build@latest

      - uses: retypeapp/action-github-pages@latest
        with:
          update-branch: true
